backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "videos"
    label: "Videos"
    folder: "content/videos"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Vimeo Video ID", name: "vimeo_id", widget: "string", hint: "Örn: 1196732175"}
